<a href="https://colab.research.google.com/github/lbayly-dev/CCRB-data/blob/main/NYPD_Officer_360.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import requests
import pandas as pd
import io
import matplotlib.pyplot as plt
import seaborn as sns

# Pulling Police Officer csv file from the NYC Open Data Portal
csv_url = 'https://data.cityofnewyork.us/api/views/2fir-qns4/rows.csv?accessType=DOWNLOAD'

try:
    # Send a GET request to the URL
    response = requests.get(csv_url)
    response.raise_for_status() # Raise an exception for HTTP errors (4xx or 5xx)

    # Read the content into a pandas DataFrame
    df = pd.read_csv(io.StringIO(response.text))

    print(f"Successfully downloaded CSV from {csv_url} and loaded into a DataFrame.")

    # Display the first 5 rows of the DataFrame
    display(df.head())

except requests.exceptions.RequestException as e:
    print(f"Error downloading the CSV file: {e}")
except pd.errors.EmptyDataError:
    print("Error: The downloaded file is empty or not a valid CSV.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Successfully downloaded CSV from https://data.cityofnewyork.us/api/views/2fir-qns4/rows.csv?accessType=DOWNLOAD and loaded into a DataFrame.

,As Of Date,Tax ID,Active Per Last Reported Status,Last Reported Active Date,Officer First Name,Officer Last Name,Officer Race,Officer Gender,Current Rank Abbreviation,Current Rank,Current Command,Shield No,Total Complaints,Total Substantiated Complaints
0,05/30/2026,974766,Yes,05/01/2026 04:31:35 PM,Jerry,Brown,Black,Male,PO,Police Officer,107 PCT,16200.0,1,1
1,05/30/2026,945434,Yes,05/01/2026 04:31:35 PM,Carlos,Perez,Hispanic,Male,SGT,Sergeant,MELD,4256.0,3,0
2,05/30/2026,968487,No,02/03/2025 10:54:00 AM,Nicholas,Hernandez,Hispanic,Male,PO,Police Officer,094 PCT,8647.0,1,0
3,05/30/2026,962389,Yes,05/01/2026 04:31:35 PM,Marleny,Estevez,Hispanic,Female,DT3,Detective,BX CHILD,7195.0,3,1
4,05/30/2026,972923,No,01/04/2023 10:52:01 AM,Denise,Rosado,Hispanic,Female,PO,Police Officer,033 PCT,576.0,0,0

In [2]:
# Pulling Allegations csv file from the NYC Open Data Portal
allegations_url = 'https://data.cityofnewyork.us/api/views/6xgr-kwjq/rows.csv?accessType=DOWNLOAD'

try:
    response_allegations = requests.get(allegations_url)
    response_allegations.raise_for_status()
    df_allegations = pd.read_csv(io.StringIO(response_allegations.text))

    print(f"Successfully downloaded CSV from {allegations_url} and loaded into df_allegations.")
    display(df_allegations.head())

except requests.exceptions.RequestException as e:
    print(f"Error downloading the Allegations CSV file: {e}")
except pd.errors.EmptyDataError:
    print("Error: The downloaded Allegations file is empty or not a valid CSV.")
except Exception as e:
    print(f"An unexpected error occurred with Allegations CSV: {e}")

Successfully downloaded CSV from https://data.cityofnewyork.us/api/views/6xgr-kwjq/rows.csv?accessType=DOWNLOAD and loaded into df_allegations.

,As Of Date,Complaint Id,Complaint Officer Number,Tax ID,Officer Rank Abbreviation At Incident,Officer Rank At Incident,Officer Command At Incident,Officer Days On Force At Incident,Allegation Record Identity,FADO Type,Allegation,Victim/Alleged Victim Age Range At Incident,Victim/Alleged Victim Gender,Victim / Alleged Victim Race (Legacy),Victim / Alleged Victim Race / Ethnicity,CCRB Investigations Division Recommendation,CCRB Allegation Disposition,NYPD Allegation Disposition
0,05/30/2026,201301920,1,946693.0,POM,Police Officer,026 PCT,1702.0,857161,Discourtesy,Word,20 < Age <= 24,Male/Man,Black,NaN,Unsubstantiated,Unsubstantiated,NaN
1,05/30/2026,201406761,5,933900.0,POM,Police Officer,105 PCT,3819.0,917127,Force,Physical force,34 < Age <= 39,Female/Woman,Black,NaN,Exonerated,Unsubstantiated,NaN
2,05/30/2026,200514689,1,NaN,NaN,NaN,NaN,0.0,433379,Discourtesy,Word,NaN,Male/Man,Unknown,NaN,Alleged Victim Uncooperative,Alleged Victim Uncooperative,NaN
3,05/30/2026,200604768,2,903430.0,POM,Police Officer,006 PCT,4604.0,452938,Force,Physical force,24 < Age <= 29,Male/Man,Black,NaN,Exonerated,Exonerated,NaN
4,05/30/2026,200401643,1,891618.0,POM,Police Officer,043 PCT,6244.0,347689,Abuse of Authority,Refusal to provide name/shield number,NaN,Female/Woman,Hispanic,NaN,Complainant Uncooperative,Complainant Uncooperative,NaN

In [3]:
# Pulling Complaints csv file from the NYC Open Data Portal
complaints_url = 'https://data.cityofnewyork.us/api/views/2mby-ccnw/rows.csv?accessType=DOWNLOAD'

try:
    response_complaints = requests.get(complaints_url)
    response_complaints.raise_for_status()
    df_complaints = pd.read_csv(io.StringIO(response_complaints.text))

    print(f"Successfully downloaded CSV from {complaints_url} and loaded into df_complaints.")
    display(df_complaints.head())

except requests.exceptions.RequestException as e:
    print(f"Error downloading the Complaints CSV file: {e}")
except pd.errors.EmptyDataError:
    print("Error: The downloaded Complaints file is empty or not a valid CSV.")
except Exception as e:
    print(f"An unexpected error occurred with Complaints CSV: {e}")

Successfully downloaded CSV from https://data.cityofnewyork.us/api/views/2mby-ccnw/rows.csv?accessType=DOWNLOAD and loaded into df_complaints.

,As Of Date,Complaint Id,Incident Date,Incident Hour,CCRB Received Date,Close Date,Borough Of Incident Occurrence,Precinct Of Incident Occurrence,Location Type Of Incident,Reason for Police Contact,Outcome Of Police Encounter,CCRB Complaint Disposition,BWC Evidence,Video Evidence
0,20260530,201705567,2017-07-09,3.0,07/10/2017 04:03:49 PM,08/08/2017 02:53:32 PM,Bronx,52,Apartment/house,Report of other crime,No arrest made or summons issued,Closed - Pending Litigation,No,No
1,20260530,202504845,2025-05-06,18.0,05/19/2025 05:17:00 PM,08/12/2025 03:58:10 PM,Manhattan,10,NYCHA,Other,Arrest - disorderly/OGA/resisting,Complainant Unavailable,No,No
2,20260530,202007361,2020-10-17,3.0,11/06/2020 10:58:00 AM,03/30/2022 11:37:10 AM,Brooklyn,73,Apartment/house,Report-domestic dispute,No arrest made or summons issued,Unsubstantiated,Yes,No
3,20260530,200708806,2007-05-28,10.0,06/20/2007 12:00:00 AM,08/24/2007 10:00:39 AM,Brooklyn,71,Street/highway,Parking violation,Summons - other violation/crime,Mediated,No,No
4,20260530,200201850,2002-03-14,21.0,03/20/2002 04:39:33 PM,09/26/2002 02:52:34 PM,Brooklyn,77,Street/highway,Other,Arrest - other violation/crime,Unsubstantiated,No,No

In [4]:
# Filter file for active officers
filtered_df = (df['Active Per Last Reported Status'] == 'Yes')

# Convert filtered_df Series to a DataFrame containing only active officers
active_officers_df = df[filtered_df].copy()

# Perform an inner join between active_officers_df and df_allegations on 'Tax ID'
merged_active_officers_allegations = pd.merge(active_officers_df, df_allegations, on='Tax ID', how='inner', suffixes=('_officer', '_allegation'))

print(merged_active_officers_allegations.columns.tolist())

# Perform an inner join between merged_active_officers_allegations and df_complaints on 'Complaint Id'
merged_active_officers_allegations_complaints = pd.merge(merged_active_officers_allegations, df_complaints, on='Complaint Id', how='inner', suffixes=('_allegation_complaint', '_incident_detail'))

print(merged_active_officers_allegations_complaints.columns.tolist())

# Filter file for incidents in a particular borough (Manhattan, Queens, Brooklyn, Bronx, Staten Island)

# Define the desired borough for filtering
desired_borough = 'Manhattan' # You can change this to 'Queens', 'Brooklyn', 'Bronx', 'Staten Island', or any other string to test the validation

valid_boroughs = ['Manhattan', 'Queens', 'Brooklyn', 'Bronx', 'Staten Island']

if desired_borough in valid_boroughs:
    filtered_merged_df = merged_active_officers_allegations_complaints[merged_active_officers_allegations_complaints['Borough Of Incident Occurrence'] == desired_borough].copy()
    print(f"\nFiltering for incidents in {desired_borough}.")
else:
    print(f"\nError: '{desired_borough}' is not a valid borough. Please choose from {', '.join(valid_boroughs)}.")
    filtered_merged_df = pd.DataFrame(columns=merged_active_officers_allegations_complaints.columns) # Create an empty DataFrame with the same columns if input is invalid

print("\nShape of the complaints DataFrame (df_complaints):")
print(df_complaints.shape)
print("Shape of the allegations DataFrame (merged_active_officers_allegations):")
print(merged_active_officers_allegations.shape)
print("Shape of the inner merged DataFrame before penalties:")
print(merged_active_officers_allegations_complaints.shape)
print(f"Shape of the filtered inner merged DataFrame ({desired_borough}):") # Dynamically update this print
print(filtered_merged_df.shape)

['As Of Date_officer', 'Tax ID', 'Active Per Last Reported Status', 'Last Reported Active Date', 'Officer First Name', 'Officer Last Name', 'Officer Race', 'Officer Gender', 'Current Rank Abbreviation', 'Current Rank', 'Current Command', 'Shield No', 'Total Complaints', 'Total Substantiated Complaints', 'As Of Date_allegation', 'Complaint Id', 'Complaint Officer Number', 'Officer Rank Abbreviation At Incident', 'Officer Rank At Incident', 'Officer Command At Incident', 'Officer Days On Force At Incident', 'Allegation Record Identity', 'FADO Type', 'Allegation', 'Victim/Alleged Victim Age Range At Incident', 'Victim/Alleged Victim Gender', 'Victim / Alleged Victim Race (Legacy)', 'Victim / Alleged Victim Race / Ethnicity', 'CCRB Investigations Division Recommendation', 'CCRB Allegation Disposition', 'NYPD Allegation Disposition']
['As Of Date_officer', 'Tax ID', 'Active Per Last Reported Status', 'Last Reported Active Date', 'Officer First Name', 'Officer Last Name', 'Officer Race', 'Officer Gender', 'Current Rank Abbreviation', 'Current Rank', 'Current Command', 'Shield No', 'Total Complaints', 'Total Substantiated Complaints', 'As Of Date_allegation', 'Complaint Id', 'Complaint Officer Number', 'Officer Rank Abbreviation At Incident', 'Officer Rank At Incident', 'Officer Command At Incident', 'Officer Days On Force At Incident', 'Allegation Record Identity', 'FADO Type', 'Allegation', 'Victim/Alleged Victim Age Range At Incident', 'Victim/Alleged Victim Gender', 'Victim / Alleged Victim Race (Legacy)', 'Victim / Alleged Victim Race / Ethnicity', 'CCRB Investigations Division Recommendation', 'CCRB Allegation Disposition', 'NYPD Allegation Disposition', 'As Of Date', 'Incident Date', 'Incident Hour', 'CCRB Received Date', 'Close Date', 'Borough Of Incident Occurrence', 'Precinct Of Incident Occurrence', 'Location Type Of Incident', 'Reason for Police Contact', 'Outcome Of Police Encounter', 'CCRB Complaint Disposition', 'BWC Evidence', 'Video Evidence']

Filtering for incidents in Manhattan.

Shape of the complaints DataFrame (df_complaints):
(139974, 14)
Shape of the allegations DataFrame (merged_active_officers_allegations):
(124848, 31)
Shape of the inner merged DataFrame before penalties:
(124848, 44)
Shape of the filtered inner merged DataFrame (Manhattan):
(26527, 44)

In [5]:
# Print columns in file to decide which columns to keep
print(filtered_merged_df.columns.tolist())

['As Of Date_officer', 'Tax ID', 'Active Per Last Reported Status', 'Last Reported Active Date', 'Officer First Name', 'Officer Last Name', 'Officer Race', 'Officer Gender', 'Current Rank Abbreviation', 'Current Rank', 'Current Command', 'Shield No', 'Total Complaints', 'Total Substantiated Complaints', 'As Of Date_allegation', 'Complaint Id', 'Complaint Officer Number', 'Officer Rank Abbreviation At Incident', 'Officer Rank At Incident', 'Officer Command At Incident', 'Officer Days On Force At Incident', 'Allegation Record Identity', 'FADO Type', 'Allegation', 'Victim/Alleged Victim Age Range At Incident', 'Victim/Alleged Victim Gender', 'Victim / Alleged Victim Race (Legacy)', 'Victim / Alleged Victim Race / Ethnicity', 'CCRB Investigations Division Recommendation', 'CCRB Allegation Disposition', 'NYPD Allegation Disposition', 'As Of Date', 'Incident Date', 'Incident Hour', 'CCRB Received Date', 'Close Date', 'Borough Of Incident Occurrence', 'Precinct Of Incident Occurrence', 'Location Type Of Incident', 'Reason for Police Contact', 'Outcome Of Police Encounter', 'CCRB Complaint Disposition', 'BWC Evidence', 'Video Evidence']

In [6]:
# Drop the columns that are not needed - can easily be edited to include or remove columns. Code in the line above prints all column names before filtering for reference.
filtered_merged_df = filtered_merged_df.drop(columns=['Victim / Alleged Victim Race (Legacy)', 'Active Per Last Reported Status', 'Last Reported Active Date', 'As Of Date_allegation', 'As Of Date', 'CCRB Investigations Division Recommendation'])

print(filtered_merged_df.columns.tolist())

['As Of Date_officer', 'Tax ID', 'Officer First Name', 'Officer Last Name', 'Officer Race', 'Officer Gender', 'Current Rank Abbreviation', 'Current Rank', 'Current Command', 'Shield No', 'Total Complaints', 'Total Substantiated Complaints', 'Complaint Id', 'Complaint Officer Number', 'Officer Rank Abbreviation At Incident', 'Officer Rank At Incident', 'Officer Command At Incident', 'Officer Days On Force At Incident', 'Allegation Record Identity', 'FADO Type', 'Allegation', 'Victim/Alleged Victim Age Range At Incident', 'Victim/Alleged Victim Gender', 'Victim / Alleged Victim Race / Ethnicity', 'CCRB Allegation Disposition', 'NYPD Allegation Disposition', 'Incident Date', 'Incident Hour', 'CCRB Received Date', 'Close Date', 'Borough Of Incident Occurrence', 'Precinct Of Incident Occurrence', 'Location Type Of Incident', 'Reason for Police Contact', 'Outcome Of Police Encounter', 'CCRB Complaint Disposition', 'BWC Evidence', 'Video Evidence']

In [7]:
# Reformat dates so that they can be read by AirTable, and will be consistently rendered.
date_columns = [
    'As Of Date_officer',
    'Incident Date',
    'CCRB Received Date',
    'Close Date'
]

for col in date_columns:
    if col in filtered_merged_df.columns:
        # Convert to datetime, coercing errors will turn unparseable dates into NaT (Not a Time)
        filtered_merged_df[col] = pd.to_datetime(filtered_merged_df[col], errors='coerce')
        # Format as 'YYYY-MM-DD' string, NaT values will become NaN
        filtered_merged_df[col] = filtered_merged_df[col].dt.strftime('%Y-%m-%d')

print("Date columns formatted to 'YYYY-MM-DD'. Displaying first 5 rows to verify:")
display(filtered_merged_df[date_columns].head())

/tmp/ipykernel_454/2064754573.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  filtered_merged_df[col] = pd.to_datetime(filtered_merged_df[col], errors='coerce')

Date columns formatted to 'YYYY-MM-DD'. Displaying first 5 rows to verify:

  As Of Date_officer Incident Date CCRB Received Date  Close Date
1         2026-05-30    2008-12-03         2008-12-09  2010-04-09
2         2026-05-30    2011-04-19         2011-04-19  2011-05-23
3         2026-05-30    2008-12-03         2008-12-09  2010-04-09
4         2026-05-30    2008-10-05         2008-10-09  2009-01-21
5         2026-05-30    2008-12-03         2008-12-09  2010-04-09

In [8]:
# Export the filtered DataFrame to a CSV file. Be sure to rename the file as appropriate if filtering by another borough.
output_manhattan_rows = 'manhattan_police_complaints.csv'
filtered_merged_df.to_csv(output_manhattan_rows, index=False)

# Download the csv file
from google.colab import files
files.download('manhattan_police_complaints.csv')